"""Model card: every hyperparameter and every weight tensor of a run, generated from the code.

    uv run python -m mdlm.describe --preset small-768 --run pilot120m --out docs/pilot120m.md

mdlm.train writes the same card to runs/<run>/MODEL_CARD.md when a run starts, so
the documentation always matches what was trained.
"""
from __future__ import annotations

import argparse
import dataclasses
import hashlib
import json
import math
import platform
from pathlib import Path

import torch

from tokenizer import VOCAB_PATH, load_default

from .diffusion import CE_CHUNK, EPS
from .model import PRESETS, Denoiser, ModelConfig
from .train import TrainConfig

MEASURED_TOK_S = {"small-768": 20939, "small-512": 36310}    # RTX 5050 Laptop, mdlm.benchmark, micro-batch 16


def _fields_table(cfg) -> list[str]:
    rows = ["| field | value | meaning |", "|---|---|---|"]
    for f in dataclasses.fields(cfg):
        rows.append(f"| `{f.name}` | `{getattr(cfg, f.name)}` | {f.metadata.get('doc', '')} |")
    return rows


def _init_note(name: str, mcfg: ModelConfig) -> str:
    if name.endswith("norm1.weight") or name.endswith("norm2.weight") or name == "norm.weight":
        return "ones"
    if name.endswith("proj.weight") or name.endswith("down.weight"):
        return f"N(0, {mcfg.init_std / math.sqrt(2 * mcfg.n_layers):.5f})"
    return f"N(0, {mcfg.init_std})"


def _role(name: str) -> str:
    return {"embed.weight": "token embedding; tied: also the output layer (logits = h · Eᵀ)",
            "norm.weight": "final RMSNorm gain"}.get(name) or {
        "norm1.weight": "RMSNorm gain before attention",
        "qkv.weight": "fused query/key/value projection",
        "proj.weight": "attention output projection (residual branch)",
        "norm2.weight": "RMSNorm gain before the MLP",
        "gate_up.weight": "fused SwiGLU gate and up projections",
        "down.weight": "SwiGLU down projection (residual branch)",
    }.get(name.split(".", 2)[-1], "")


def model_card(mcfg: ModelConfig, tcfg: TrainConfig, corpus_meta: dict | None = None) -> str:
    tok = load_default()
    with torch.device("meta"):
        model = Denoiser(mcfg)
    total, non_emb = model.num_params(False), model.num_params()
    emb = total - non_emb
    tokens_per_step = tcfg.batch_size * tcfg.seq_len
    total_tokens = tokens_per_step * tcfg.total_steps
    L = [f"# Model card — `{tcfg.run}` ({tcfg.preset})", "",
         "Generated by `mdlm.describe` from the code and configuration that the run uses.", "",
         "## Summary", "",
         f"- Masked diffusion language model (MDLM, Sahoo et al. 2024) for Telugu, trained from scratch.",
         f"- **{total:,} parameters**: {non_emb:,} in the transformer, {emb:,} in the tied embedding "
         f"({mcfg.padded_vocab:,} × {mcfg.d_model}).",
         f"- {mcfg.n_layers} blocks × d_model {mcfg.d_model}, {mcfg.n_heads} heads × {mcfg.head_dim}, "
         f"SwiGLU {mcfg.mlp_hidden}, canvas {mcfg.max_len} tokens.",
         f"- Training: {tcfg.total_steps:,} steps × {tokens_per_step:,} tokens = **{total_tokens / 1e9:.2f}B tokens** "
         f"({total_tokens / total:.0f} tokens per parameter)."]
    if tcfg.preset in MEASURED_TOK_S:
        hours = total_tokens / MEASURED_TOK_S[tcfg.preset] / 3600
        L.append(f"- Measured speed on the RTX 5050 Laptop: {MEASURED_TOK_S[tcfg.preset]:,} tokens/s, "
                 f"so about {hours:.0f} h ({hours / 24:.1f} days) of pure training.")

    L += ["", "## Architecture hyperparameters", ""] + _fields_table(mcfg) + [
          "", f"Derived: head_dim = {mcfg.head_dim}; padded vocabulary = {mcfg.padded_vocab:,} "
              f"(vocab_size rounded up to a multiple of 128; the {mcfg.padded_vocab - mcfg.vocab_size} padding rows are never predicted).",
          "", "## Fixed design choices (not configurable)", "",
          "| choice | setting |", "|---|---|",
          "| block layout | pre-norm: x + Attn(RMSNorm(x)), then x + SwiGLU(RMSNorm(x)); final RMSNorm before the output layer |",
          "| attention | bidirectional (no causal mask), `F.scaled_dot_product_attention`, softmax scale 1/√head_dim |",
          "| positions | rotary embeddings (RoPE) on queries and keys, interleaved channel pairs, no learned position embedding |",
          "| MLP | SwiGLU: down(SiLU(gate(x)) ⊙ up(x)) |",
          "| biases | none (every linear layer is bias-free) |",
          "| dropout | none |",
          "| time conditioning | none: the absorbing-state denoiser's optimum is independent of t (Ou et al. 2024; Zheng et al. 2024) |",
          "| embeddings | input and output tied (one matrix) |",
          "| precision | fp32 master weights and optimizer state; bf16 autocast for the forward/backward; fp32 cross-entropy |",
          "", "## Every weight tensor", "",
          "| tensor | shape | parameters | init | weight decay | role |", "|---|---|---|---|---|---|"]
    for name, p in model.named_parameters():
        L.append(f"| `{name}` | {tuple(p.shape)} | {p.numel():,} | {_init_note(name, mcfg)} | "
                 f"{tcfg.weight_decay if p.dim() >= 2 else 0} | {_role(name)} |")
    L += [f"| **total** | | **{total:,}** | | | |"]
    per_block = sum(p.numel() for p in model.blocks[0].parameters())
    L += ["", f"Per block: {per_block:,} parameters × {mcfg.n_layers} blocks = {per_block * mcfg.n_layers:,}; "
              f"plus the final norm ({mcfg.d_model}) and the embedding ({emb:,}).",
          "", "## Diffusion objective", "",
          "| item | setting |", "|---|---|",
          "| forward process | absorbing state: each token becomes `<mask>` independently with probability t (log-linear schedule, α_t = 1 − t) |",
          f"| time sampling | t ~ U(ε, 1) with ε = {EPS}, low-discrepancy: one offset u, t_i = ε + (1 − ε)·((u + i/B) mod 1) across the batch |",
          "| parameterisation | SUBS: `<mask>`, `<pad>`, `<unk>` and padding logits are −∞; unmasked tokens are copied (no loss) |",
          "| loss | NELBO per token = Σ over masked positions of CE / t, divided by batch × length (nats/token; exp gives a perplexity bound) |",
          f"| memory | output layer evaluated only at masked positions, in chunks of {CE_CHUNK:,} whose logits are recomputed in the backward pass |",
          "", "## Training hyperparameters", ""] + _fields_table(tcfg) + [
          "", "Derived settings:", "",
          f"- Tokens per optimizer step: {tokens_per_step:,}; gradient accumulation: {tcfg.batch_size // tcfg.micro_batch} passes of {tcfg.micro_batch}.",
          f"- Learning rate: linear warm-up to {tcfg.lr} over {tcfg.warmup_steps:,} steps, then cosine decay to "
          f"{tcfg.lr * tcfg.min_lr_ratio:.1e} at step {tcfg.total_steps:,}.",
          f"- AdamW (fused): betas (0.9, {tcfg.beta2}), eps 1e-8; two parameter groups: matrices "
          f"(weight decay {tcfg.weight_decay}) and RMSNorm gains (no decay).",
          f"- Total: {total_tokens:,} tokens."]

    L += ["", "## Data", ""]
    if corpus_meta:
        L += ["| source | train tokens | weight | tokens seen | passes |", "|---|---|---|---|---|"]
        for src, w in tcfg.weights.items():
            n = corpus_meta["funnel"].get(src, {}).get("train_tokens", 0)
            seen = total_tokens * w / sum(tcfg.weights.values())
            L.append(f"| {src} | {n:,} | {w:.0%} | {seen / 1e9:.2f}B | {seen / n:.2f} |" if n else f"| {src} | ? | {w:.0%} | | |")
        L += ["", f"Corpus built {corpus_meta['finished']} by `data_prep.build_corpus` (see `pretraining_datasets/tokens/report.md`).", ""]
    L += ["- A training window is 512 consecutive tokens from a random offset in the chosen source's `train.bin`; "
          "documents are stored as `<bos> … <eos>` and a window may span several (MDLM's wrapped setting).",
          "- Batch composition, times and masks are a pure function of (seed, step), so resumed runs see the same data.",
          "", "## Tokenizer", "",
          f"- `{VOCAB_PATH.relative_to(VOCAB_PATH.parents[2])}` "
          f"(sha256 `{hashlib.sha256(VOCAB_PATH.read_bytes()).hexdigest()}`), {tok.vocab_size:,} tokens.",
          f"- Specials: `<pad>`={tok.pad_id}, `<unk>`={tok.unk_id}, `<bos>`={tok.bos_id}, `<eos>`={tok.eos_id}, "
          f"`<mask>`={tok.special_to_id['<mask>']}.",
          "- One token per akshara, split by `meter_engine/aksharanusarika.py` (ఁ stays on its akshara, ZWNJ is stripped); "
          "rare aksharas fall back to byte-level BPE, so nothing is ever out of vocabulary.",
          "", "## Evaluation and sampling", "",
          f"- Every {tcfg.eval_every:,} steps, with the EMA weights: validation NELBO and perplexity bound per source on "
          f"{tcfg.eval_canvases} fixed canvases each (fixed times and masks); cross-entropy by mask-rate bin; masked-token "
          "accuracy at 15 / 50 / 85 % masking.",
          f"- Every {tcfg.sample_every:,} steps: {tcfg.n_samples} samples of {tcfg.seq_len} tokens with the ancestral sampler "
          f"({tcfg.sample_steps} steps, float64 Gumbel draws); logged: token entropy, distinct-1/2/3, repeated 4-grams, "
          "rare-akshara share, dangling viramas, Telugu share, share of words attested in validation text.",
          "- Offline: generative perplexity with `mdlm.judge` (google/gemma-3-1b-pt; real Telugu 17.6, word-shuffled 70.6).",
          "", "## Checkpoints and recovery", "",
          f"- Two alternating fsync'ed slots `ckpt_a.pt` / `ckpt_b.pt` (model, EMA, optimizer, step); saved every "
          f"{tcfg.ckpt_every_min:g} min, on Ctrl-C/SIGTERM, at once when mains power is lost, every {tcfg.battery_ckpt_min:g} min "
          f"on battery, and before exiting at {tcfg.battery_stop_percent} % battery. Re-running the command resumes from the "
          "newest readable slot.",
          f"- Permanent bf16 EMA snapshots every {tcfg.snapshot_every:,} steps in `snapshots/`.",
          "- CUDA out-of-memory during a step: partial gradients are cleared and the step is retried with half the "
          "micro-batch (same computation, smaller pieces). During evaluation, sampling or a snapshot: that item is "
          "skipped. A non-finite loss or gradient skips the update; 100 in a row stops the run with exit code 3.",
          "- Supervisor: `deploy/telugu-mdlm-pilot.service` (systemd user service) restarts the trainer 60 s after any "
          "crash, starts it at boot, and holds sleep/idle/lid-switch inhibitors so the laptop does not suspend. "
          "Exit codes: 0 finished or stopped, 75 low battery (restart; waits for mains), 3 diverged (no restart).",
          "", "## Growth compatibility", "",
          "The model is shaped so it can later be grown into larger models, each initialised from the previous one "
          "function-preservingly (the grown model starts with exactly the same outputs):",
          "",
          "- head_dim fixed at 64 and the same RoPE base: grow by adding heads, never by widening them.",
          "- mlp_hidden = 8/3 × d_model, and each stage's d_model a whole multiple of the previous one: width grows by "
          "cloning units and heads with rescaled weights (HyperCloning-style).",
          "- Depth grows by inserting blocks whose residual output projections start at zero (identity blocks).",
          "- Same tokenizer, vocabulary, padding and tied embeddings at every stage.",
          "", "| preset | d_model × layers | heads | parameters |", "|---|---|---|---|"]
    for name in ("small-768", "grow-1536x16", "grow-1536x32", "grow-2304x16"):
        c = dataclasses.replace(PRESETS[name], vocab_size=mcfg.vocab_size)
        with torch.device("meta"):
            n = Denoiser(c).num_params(False)
        L.append(f"| `{name}` | {c.d_model} × {c.n_layers} | {c.n_heads} × {c.head_dim} | {n / 1e6:,.0f}M |")
    L += ["", "## Environment", "",
          f"- PyTorch {torch.__version__} (CUDA {torch.version.cuda}), Python {platform.python_version()}"
          + (f", GPU {torch.cuda.get_device_name(0)}" if torch.cuda.is_available() else "") + "."]
    return "\n".join(L) + "\n"


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--preset", default="small-768")
    ap.add_argument("--run", default="pilot120m")
    ap.add_argument("--out", type=Path, required=True)
    args = ap.parse_args(argv)
    tcfg = TrainConfig(run=args.run, preset=args.preset)
    tok = load_default()
    mcfg = dataclasses.replace(PRESETS[args.preset], vocab_size=tok.vocab_size, max_len=tcfg.seq_len)
    meta_path = Path(tcfg.token_dir) / "meta.json"
    meta = json.loads(meta_path.read_text(encoding="utf-8")) if meta_path.exists() else None
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(model_card(mcfg, tcfg, meta), encoding="utf-8")
    print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
